<script setup>
import Chart from 'chart.js/auto'
import { getRelativePosition } from 'chart.js/helpers'
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue'
import { downloadChartAsPNG } from '@/utils/downloadChart.js'
import { getThemeColors, DIMMED_COLOR, starPointStyles } from '@/utils/analysisCharts.js'

/*
  Proper-motion vector-point diagram (pmRA vs pmDec) of the Gaia-matched stars.
  Cluster stars share a common space motion, so they clump together while field stars
  spread out. The membership selection is drawn as a circle overlay (in data units, so
  it renders as an ellipse in pixels) and is directly draggable:
    - drag inside the circle to move its center
    - drag its edge to grow/shrink the radius
    - drag on an empty plot (no active selection) to create one
  Updates are emitted through v-model:selection; the numeric MembershipControls stay
  available for precise entry.
*/

const props = defineProps({
  cmd: {
    type: Array,
    required: true
  },
  // the membership selection {pmra, pmdec, pm_radius, ...} drawn and edited on the plot
  selection: {
    type: Object,
    default: null
  },
  // per-star member flags aligned with cmd, or null when no selection is active
  memberFlags: {
    type: Array,
    default: null
  }
})

const emit = defineEmits(['update:selection'])

const properMotionCanvas = ref(null)
let properMotionChart = null
let themeColors = {}

// clamp the axes to the bulk of the distribution so extreme field stars don't shrink the clump
const BOUND_QUANTILE = 0.05
const BOUND_PADDING_FRACTION = 0.3
const MIN_HALF_RANGE = 5.0
// selection dragging
const EDGE_GRAB_PIXELS = 10
const MIN_PM_RADIUS = 0.1

// point objects depend only on the cmd data, never on the membership selection, so
// their identity is stable while the selection circle is dragged (cmdIndex keys the
// star back into memberFlags)
const gaiaPoints = computed(() => {
  const points = []
  props.cmd.forEach((star, index) => {
    if (star.gaia_match && Number.isFinite(star.pmra) && Number.isFinite(star.pmdec)) {
      points.push({
        x: star.pmra,
        y: star.pmdec,
        star: star,
        cmdIndex: index
      })
    }
  })
  return points
})

function quantileBounds(values) {
  const sorted = [...values].sort((a, b) => a - b)
  const lower = sorted[Math.floor(BOUND_QUANTILE * (sorted.length - 1))]
  const upper = sorted[Math.ceil((1 - BOUND_QUANTILE) * (sorted.length - 1))]
  const padding = Math.max((upper - lower) * BOUND_PADDING_FRACTION, MIN_HALF_RANGE - (upper - lower) / 2)
  return { min: lower - padding, max: upper + padding }
}

function axisBounds() {
  const points = gaiaPoints.value
  if (!points.length) return { x: { min: -20, max: 20 }, y: { min: -20, max: 20 } }
  return {
    x: quantileBounds(points.map((point) => point.x)),
    y: quantileBounds(points.map((point) => point.y))
  }
}

function pointStyles() {
  return starPointStyles(gaiaPoints.value, { memberFlags: props.memberFlags, themeColors })
}

function buildDataset() {
  const { colors, radii, shapes } = pointStyles()
  return {
    data: gaiaPoints.value,
    parsing: false,
    pointBackgroundColor: colors,
    pointBorderColor: colors,
    pointRadius: radii,
    pointStyle: shapes,
    pointHoverRadius: 5,
    pointHoverBackgroundColor: themeColors.secondary,
    pointHoverBorderColor: themeColors.secondary
  }
}

// the legend is informational (the member/field split is per-point color, not
// per-dataset), so its entries are generated by hand
function legendLabels() {
  const entries = [
    { text: 'Members', fillStyle: themeColors.primary, strokeStyle: themeColors.primary, pointStyle: 'circle', fontColor: themeColors.text },
    { text: 'Field stars', fillStyle: DIMMED_COLOR, strokeStyle: DIMMED_COLOR, pointStyle: 'circle', fontColor: themeColors.text }
  ]
  if (gaiaPoints.value.some((point) => point.star.gaia_only)) {
    entries.push({ text: 'Gaia catalog', fillStyle: themeColors.primary, strokeStyle: themeColors.primary, pointStyle: 'triangle', fontColor: themeColors.text })
  }
  return entries
}

function selectionActive() {
  const selection = props.selection
  return selection && Number.isFinite(selection.pmra) && Number.isFinite(selection.pmdec)
    && Number.isFinite(selection.pm_radius)
}

// the selection circle's center and radii in pixel space (an ellipse, since the scales differ).
// Takes the chart as an argument because plugins can fire during the Chart constructor's first
// synchronous draw, before the component's chart variable is assigned
function selectionEllipse(chart) {
  const selection = props.selection
  const xScale = chart.scales.x
  const yScale = chart.scales.y
  const centerX = xScale.getPixelForValue(selection.pmra)
  const centerY = yScale.getPixelForValue(selection.pmdec)
  return {
    centerX: centerX,
    centerY: centerY,
    radiusX: Math.abs(xScale.getPixelForValue(selection.pmra + selection.pm_radius) - centerX),
    radiusY: Math.abs(yScale.getPixelForValue(selection.pmdec + selection.pm_radius) - centerY)
  }
}

// draws the pm_radius selection circle
const selectionRegionPlugin = {
  id: 'pmSelectionRegion',
  afterDatasetsDraw(chart) {
    if (!selectionActive()) return
    const { centerX, centerY, radiusX, radiusY } = selectionEllipse(chart)

    const { ctx } = chart
    ctx.save()
    ctx.strokeStyle = themeColors.secondary
    ctx.lineWidth = 2
    ctx.setLineDash([6, 4])
    ctx.beginPath()
    ctx.ellipse(centerX, centerY, radiusX, radiusY, 0, 0, 2 * Math.PI)
    ctx.stroke()
    ctx.restore()
  }
}

/* ---- direct manipulation of the selection circle ---- */

let dragMode = null   // 'move' | 'resize' | 'create' | null
let dragOffset = { x: 0, y: 0 }
let createAnchor = null
let pendingSelection = null
let emitScheduled = false

// round emitted selection values to 3 decimals (~milliarcsec)
function round3(value) {
  return Math.round(value * 1000) / 1000
}

// live-updating three charts on every pointermove is wasteful, so emit once per frame
function emitSelection(updates) {
  pendingSelection = { ...props.selection, ...updates }
  if (emitScheduled) return
  emitScheduled = true
  requestAnimationFrame(() => {
    emit('update:selection', pendingSelection)
    pendingSelection = null
    emitScheduled = false
  })
}

function pointerPosition(event) {
  const position = getRelativePosition(event, properMotionChart)
  return {
    pixelX: position.x,
    pixelY: position.y,
    x: properMotionChart.scales.x.getValueForPixel(position.x),
    y: properMotionChart.scales.y.getValueForPixel(position.y)
  }
}

// keep the circle's center inside the plotted axis ranges - pointer capture keeps
// reporting positions past the chart edge, and a circle dragged fully off-plot
// would have nothing left to grab
function clampCenter(x, y) {
  const xScale = properMotionChart.scales.x
  const yScale = properMotionChart.scales.y
  return {
    x: Math.min(Math.max(x, xScale.min), xScale.max),
    y: Math.min(Math.max(y, yScale.min), yScale.max)
  }
}

// which part of the selection circle, if any, is under the pointer
function hitTest(pixelX, pixelY) {
  if (!selectionActive()) return null
  const { centerX, centerY, radiusX, radiusY } = selectionEllipse(properMotionChart)
  if (radiusX <= 0 || radiusY <= 0) return null
  // normalized radial coordinate: 1.0 lies exactly on the ellipse boundary
  const rho = Math.hypot((pixelX - centerX) / radiusX, (pixelY - centerY) / radiusY)
  if (Math.abs(rho - 1) * Math.min(radiusX, radiusY) <= EDGE_GRAB_PIXELS) return 'edge'
  if (rho < 1) return 'inside'
  return null
}

function onPointerDown(event) {
  const point = pointerPosition(event)
  const hit = hitTest(point.pixelX, point.pixelY)
  if (hit === 'edge') {
    dragMode = 'resize'
  }
  else if (hit === 'inside') {
    dragMode = 'move'
    dragOffset = { x: point.x - props.selection.pmra, y: point.y - props.selection.pmdec }
    properMotionChart.canvas.style.cursor = 'grabbing'
  }
  else if (!selectionActive()) {
    // dragging on an empty plot creates a selection around the anchor point
    dragMode = 'create'
    createAnchor = { x: point.x, y: point.y }
    emitSelection({ pmra: round3(point.x), pmdec: round3(point.y), pm_radius: MIN_PM_RADIUS })
  }
  else {
    return
  }
  event.target.setPointerCapture?.(event.pointerId)
  event.preventDefault()
}

function onPointerMove(event) {
  const point = pointerPosition(event)
  if (!dragMode) {
    // hover feedback only
    const hit = hitTest(point.pixelX, point.pixelY)
    properMotionChart.canvas.style.cursor =
      hit === 'edge' ? 'ew-resize' : hit === 'inside' ? 'grab' : selectionActive() ? 'default' : 'crosshair'
    return
  }
  if (dragMode === 'move') {
    const center = clampCenter(point.x - dragOffset.x, point.y - dragOffset.y)
    emitSelection({ pmra: round3(center.x), pmdec: round3(center.y) })
  }
  else if (dragMode === 'resize') {
    // both axes are mas/yr, so the radius is a plain data-space distance (same as the member predicate)
    const radius = Math.hypot(point.x - props.selection.pmra, point.y - props.selection.pmdec)
    emitSelection({ pm_radius: round3(Math.max(radius, MIN_PM_RADIUS)) })
  }
  else if (dragMode === 'create') {
    const anchor = clampCenter(createAnchor.x, createAnchor.y)
    const radius = Math.hypot(point.x - anchor.x, point.y - anchor.y)
    emitSelection({
      pmra: round3(anchor.x),
      pmdec: round3(anchor.y),
      pm_radius: round3(Math.max(radius, MIN_PM_RADIUS))
    })
  }
}

function onPointerUp(event) {
  dragMode = null
  createAnchor = null
  properMotionChart.canvas.style.cursor = 'default'
  event.target.releasePointerCapture?.(event.pointerId)
}

function attachPointerHandlers() {
  const canvas = properMotionChart.canvas
  canvas.addEventListener('pointerdown', onPointerDown)
  canvas.addEventListener('pointermove', onPointerMove)
  canvas.addEventListener('pointerup', onPointerUp)
  canvas.addEventListener('pointercancel', onPointerUp)
}

function detachPointerHandlers() {
  const canvas = properMotionChart?.canvas
  if (!canvas) return
  canvas.removeEventListener('pointerdown', onPointerDown)
  canvas.removeEventListener('pointermove', onPointerMove)
  canvas.removeEventListener('pointerup', onPointerUp)
  canvas.removeEventListener('pointercancel', onPointerUp)
}

/* ---- chart lifecycle ---- */

function tooltipLines(context) {
  const star = context.raw?.star
  if (!star) return []
  const lines = [
    `pm: ${star.pmra}, ${star.pmdec} mas/yr`,
    `parallax: ${star.parallax} mas`,
    star.gaia_only ? `Gaia catalog star (G = ${star.g_mag})` : `mag: ${star.mag}`
  ]
  // Bailer-Jones geometric distance with its 16th-84th percentile range, when the source has one
  if (star.distance != null) {
    lines.push(`distance: ${Math.round(star.distance)} pc (${Math.round(star.distance_lo)}–${Math.round(star.distance_hi)})`)
  }
  return lines
}

// restyle the existing datasets in place by changing their properties depending on the membership group they are in.
// Replacing them would recreate the chart elements and cause flickering in the points on the plot.
function updateChart() {
  const bounds = axisBounds()
  const dataset = properMotionChart.data.datasets[0]
  const { colors, radii } = pointStyles()
  dataset.data = gaiaPoints.value
  dataset.pointBackgroundColor = colors
  dataset.pointBorderColor = colors
  dataset.pointRadius = radii
  properMotionChart.options.scales.x.min = bounds.x.min
  properMotionChart.options.scales.x.max = bounds.x.max
  properMotionChart.options.scales.y.min = bounds.y.min
  properMotionChart.options.scales.y.max = bounds.y.max
  properMotionChart.options.plugins.legend.display = !!props.memberFlags
  properMotionChart.update()
}

function createChart() {
  themeColors = getThemeColors()

  const bounds = axisBounds()

  properMotionChart = new Chart(properMotionCanvas.value, {
    type: 'scatter',
    data: {
      datasets: [buildDataset()]
    },
    plugins: [selectionRegionPlugin],
    options: {
      responsive: true,
      maintainAspectRatio: false,
      animation: false,
      interaction: { mode: 'nearest', intersect: true },
      scales: {
        x: {
          type: 'linear',
          min: bounds.x.min,
          max: bounds.x.max,
          title: { display: true, text: 'pmRA (mas/yr)', color: themeColors.text },
          border: { color: themeColors.text, width: 2 },
          ticks: { color: themeColors.text },
          grid: { color: themeColors.background, tickColor: themeColors.text }
        },
        y: {
          min: bounds.y.min,
          max: bounds.y.max,
          title: { display: true, text: 'pmDec (mas/yr)', color: themeColors.text },
          border: { color: themeColors.text, width: 2 },
          ticks: { color: themeColors.text },
          grid: { color: themeColors.background, tickColor: themeColors.text }
        }
      },
      plugins: {
        legend: {
          display: !!props.memberFlags,
          // informational only: clicking must not hide the single shared dataset
          onClick: () => {},
          labels: { color: themeColors.text, usePointStyle: true, generateLabels: legendLabels }
        },
        tooltip: { callbacks: { label: tooltipLines } }
      }
    }
  })
}

watch(() => [props.cmd, props.selection, props.memberFlags], () => {
  if (properMotionChart) {
    updateChart()
  }
}, { deep: true })

onMounted(() => {
  createChart()
  attachPointerHandlers()
})

onBeforeUnmount(() => {
  detachPointerHandlers()
})

</script>
<template>
  <div class="wrapper">
    <p class="title-pm">
      Proper Motions
      <v-btn
        icon="mdi-download"
        class="download-btn"
        title="Download as PNG"
        @click="downloadChartAsPNG(properMotionChart, 'proper-motions.png', 'Proper Motions')"
      />
    </p>
    <div class="pm-plot-wrapper">
      <canvas
        ref="properMotionCanvas"
        class="pm-plot"
      />
    </div>
    <p class="drag-hint">
      Drag the circle to move it, drag its edge to resize{{ selectionActive() ? '' : ', or drag on the plot to select the cluster' }}
    </p>
  </div>
</template>

<style scoped>
.wrapper {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
}
.title-pm {
  align-self: center;
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin: 0 0 1rem;
}
.pm-plot-wrapper {
  display: flex;
  flex-direction: row;
  align-items: center;
  flex: 1;
  min-height: 0;
  width: 100%;
  position: relative;
}
.pm-plot {
  width: 100% !important;
  height: 100% !important;
  touch-action: none;
}
.drag-hint {
  align-self: center;
  font-size: 0.75rem;
  color: var(--info);
  margin: 0.25rem 0 0;
}
.download-btn {
  flex: 0 0 auto;
  width: 44px;
  height: 44px;
}
</style>
