# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: app-config
          configMap:
            name: app-config
      containers:
        - name: default
          image: datalab-ui
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 1000m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 512Mi
          volumeMounts:
            - name: app-config
              mountPath: /app/dist/config
          ports:
            - name: frontend
              containerPort: 8080
              protocol: TCP
