# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: "32Mi"
      initContainers:
        - name: copy-static-files
          image: datalab-ui
          command:
            - "sh"
            - "-c"
            - "cp -r /app/dist/* /app/volume"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 1000m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 512Mi
          volumeMounts:
            - name: dist
              mountPath: /app/volume
      containers:
        - name: default
          image: ghcr.io/static-web-server/static-web-server:2
          command:
            - /static-web-server
            - --root=/app/dist
            - --health
            - --port=8080
            - --host=0.0.0.0
            - --page-fallback=/app/dist/index.html
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 256Mi
          volumeMounts:
            - name: dist
              mountPath: /app/dist
            - name: app-config
              mountPath: /app/dist/config
          ports:
            - name: frontend
              containerPort: 8080
              protocol: TCP
