apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy-frontend/deploy.yaml
  - ./svc-frontend/svc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: datalab-ui
    includeSelectors: true
  
configMapGenerator:
  - name: app-config
    files:
      - config.json
