# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/service.json
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: server
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|Datalab'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: frontend
  ports:
  - name: frontend
    port: 8080
    targetPort: frontend
