name: "Continuous Deployment"
on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  packages: write

jobs:
  cd:
    uses: LCOGT/reusable-workflows/.github/workflows/continuous-deployment.yaml@main
    with:
      skaffoldBuildModules: "datalab-ui"
    secrets: inherit
