name: "Continuous Deployment"
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  cd:      
    uses: LCOGT/reusable-workflows/.github/workflows/continuous-deployment.yaml@f654fc1b6c3e297fccb38baf31c659899b547408
    with:
      skaffoldBuildModules: "datalab-ui"
    secrets: inherit
