name: "Continuous Deployment"
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  cd:
    permissions:
      packages: write
      contents: read
      statuses: write
      
    uses: LCOGT/reusable-workflows/.github/workflows/continuous-deployment.yaml@main
    with:
      skaffoldBuildModules: "datalab-ui"
    secrets: inherit
